SET TOKEN_FILE_NAME=token
SET NODE_LIST_FILE_NAME=nodesList
SET PLAYER_LIST_FILE_NAME=playerList
SET CSV_INPUT_FILE_NAME=Sample.csv
SET CSV_TO_TEXT_FILE_NAME=input.txt
SET OUTPUT_CSV_FILE_NAME=engine.csv
SET API_SERVER_HTTPS=0
SET API_SERVER=api.app
SET API_KEY=2683567003
SET API_SECRET=a27624468a30e220076cb5c3d037c420
SET ACTION_NAME=sell
SET GEN_CSV_ONLY=1
SET ACC_ACTION_NAME=acc

del %CSV_TO_TEXT_FILE_NAME%
del %TOKEN_FILE_NAME%
del %NODE_LIST_FILE_NAME%
del %PLAYER_LIST_FILE_NAME%
del %OUTPUT_CSV_FILE_NAME%

REM XlsToCsv Sample.xls CSV_INPUT_FILE_NAME Etopup
node loadCsv.js >> %CSV_TO_TEXT_FILE_NAME%
node getToken.js >> %TOKEN_FILE_NAME%
node getNodes.js >> %NODE_LIST_FILE_NAME%
node getPlayers.js >> %PLAYER_LIST_FILE_NAME%
IF %GEN_CSV_ONLY%==1 (
	node parseData.js >> %OUTPUT_CSV_FILE_NAME%
) ELSE (
	node parseData.js
)